### ISSUE TITLE
JSON Null Value Leads To Java Null Pointer Exception

### ISSUE THREAD

**Issue by tobiasschweizer** [carml/carml#142]
Hi there,

I ran into an issue when using CARML version 0.4.0 to map the contents of a JSON file.
I made a repo with a reproducible example: https://github.com/tobiasschweizer/carml-bug-report

Summary: when iterating over objects with `null` values in JSON (https://github.com/tobiasschweizer/carml-bug-report/blob/b386a89b00dc59e273715f2ba674e88f8cfe9fab/test-data/data2.json#L44-L49) that are used in subject and object maps, CARML throws a null pointer exception. When applying the same mapping to a file without JSON null values, it works as expected.

EDIT: sometimes it complains about not finding the data file. I just kept re-running the program until it work. Maybe I did something wrong with the file / path class.

I think it could be related to iterations as I have not experienced this problems on a top level object `null` value (no iteration involved).

Thank you very much for your support.

**Comment by pmaria** [comment]
Hi @tobiasschweizer, thanks for this easy to reproduce bug report. 
I'll have look at it this weekend and roll out a fix asap.

**Comment by tobiasschweizer** [comment]
Hello @pmaria, 
That sounds great, thanks a lot. 
Please let me know if I can be of any further assistance.

**Comment by pmaria** [comment]
Update: I've located the cause of the nullpointer bug. I think I can roll out a fix-release around Monday.

**Comment by tobiasschweizer** [comment]
That's great, thank you for doing that so quickly!

So this means that once the bug is fixed:
- no triples would be generated at all for the whole `<#OrganizationMapping>` if `id` is `null` (`id` is used in subject map)
- no triple for the object map would be generated if `country_code` is `null`

In my understanding, the value not being `null` is like a condition for a subject or object map. I tried to understand how to this for specific values, e.g. a specific string, using functions, see https://github.com/kg-construct/rml-questions/discussions/17.

**Comment by pmaria** [comment]
Yes correct if a term generating expression leads to `null` no triple generation should take place.

**Comment by pmaria** [comment]
@tobiasschweizer the bugfix has been released and should be available on maven central (soon).

**Comment by pmaria** [comment]
@tobiasschweizer ah cool. Yes, help is definitely welcome. I'll try to share the first implementation soon.

**Comment by tobiasschweizer** [comment]
That's great to hear. Just let me know when I can do something :-)
I did a lot Scala in the past few years but not really Java. So that is going to be interesting!
