### ISSUE TITLE
Fix maven build warnings

### ISSUE THREAD

**Issue by pmaria** [carml/carml#16]

**Comment by ZacharyWhitley** [comment]
I didn't notice any build warnings but I'll take a second look.

**Comment by pmaria** [comment]
I had noticed some during first release, and created this issue as a reminder to check it out. But I don't know if it is still the case. I think we can close this issue for now, if you don't find anything.

**Comment by ZacharyWhitley** [comment]
It's looking good on the develop branch for me.

**Comment by pmaria** [comment]
Cannot reproduce
