### ISSUE TITLE
IRI Generation Fails With Newlines

### ISSUE THREAD

**Issue by tobiasschweizer** [carml/carml#167]
Hi there (and do not look at this yet if you are still on vacation :-))

I ran into an issue when generating IRIs from an XML element value containing newlines.

mapping:
```ttl
PREFIX rr: <http://www.w3.org/ns/r2rml#>
PREFIX rml: <http://semweb.mmlab.be/ns/rml#>
PREFIX ql: <http://semweb.mmlab.be/ns/ql#>
PREFIX carml: <http://carml.taxonic.com/carml/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX premis: <http://id.loc.gov/vocabulary/preservation/>
PREFIX schema: <http://schema.org/>
@base <http://example.com/ns#>. 

<#LogicalSourceArticle> a rml:BaseSource ;
    rml:source "test.xml";
    rml:referenceFormulation ql:XPath ;
    rml:iterator "/result[@type='relatedResult']" .

<#article> a rr:TriplesMap ;
    rml:logicalSource <#LogicalSourceArticle> ;

    rr:subjectMap [
    	rr:template "https://data.connectome.ch/publication/{id}" ;
    	rr:class schema:ScholarlyArticle ;
    ] ;

    rr:predicateObjectMap [
    	rr:predicate schema:name ;
    	rr:objectMap [
    		rml:reference "title" ;
    	];
    ] ;

  	rr:predicateObjectMap [
  		rr:predicate schema:sameAs ;
  		rr:objectMap [
  			rr:template "https://doi.org/{identifiers/doi}" ;
  		];
  	] ;

  	rr:predicateObjectMap [
  		rr:predicate schema:author ;
  		rr:objectMap [
  			rr:template "https://data.connectome.ch/author/{details/authors/author}" ;
  		];
  	] .

```

data:
```xml
<result source="corda" type="relatedResult">


    <availableLanguages readOnly="true">en</availableLanguages>


    <rcn>486865</rcn>


    <id>633595_143290_PUBLI</id>


    <title>The Generation R Study: design and cohort update 2017</title>


    <details>


        <authors><author>Caroline C. W. Klaver</author><author>Aad van der
            Lugt</author>
        </authors>


        <journalTitle>European Journal of Epidemiology</journalTitle>


        <journalNumber>31/12</journalNumber>


        <publisher>Kluwer Academic Publishers</publisher>


        <publishedYear>2016</publishedYear>


        <publishedPages>1243-1264</publishedPages>


    </details>


    <identifiers>


        <doi>10.1007/s10654-016-0224-9</doi>


        <issn>0393-2990</issn>


    </identifiers>


    <contentUpdateDate>2020-09-10 11:07:03</contentUpdateDate>


    <relations>


        <categories>


            <category classification="collection" type="belongsTo">


                <language>en</language>


                <availableLanguages readOnly="true">de,en,es,fr,it,pl</availableLanguages>


                <code>/publication</code>


                <title>Project publication</title>


                <description>Result: Project publications</description>


                <displayCode readOnly="true">/Project publication</displayCode>


            </category>


            <category classification="projectPublication" type="isPublishedAs">


                <language>en</language>


                <availableLanguages readOnly="true">de,en,es,fr,it,pl</availableLanguages>


                <code>/PEER_REVIEWED_ARTICLE</code>


                <title>Peer reviewed articles</title>


                <displayCode readOnly="true">/Peer reviewed articles</displayCode>


            </category>


            <category classification="source" type="isProvidedBy">


                <language>en</language>


                <availableLanguages readOnly="true">de,en,es,fr,it,pl</availableLanguages>


                <code>/corda</code>


                <title>CORDA</title>


                <description>RTD research data warehouse</description>


                <displayCode readOnly="true">/CORDA</displayCode>


            </category>


        </categories>


    </relations>


</result>

```

Result with carml 0.4.2 (using CARML JAR): 
> io.carml.engine.TermGeneratorFactoryException: Could not generate a valid iri from term lexical form [https://data.connectome.ch/author/Aad%20van%20der%A%20%20%20%20%20%20%20%20%20%20%20%20Lugt] as-is, or prefixed with base iri [http://example.com/base/]

I found a solution for this by preprocessing the text (remove all newlines and trim and collapse spaces). 

Is the handling of whitespace in XML somehow specified in RML? I used to work with XML (XSLT transformations) before and whitespace was a common source of pain ...

**Comment by pmaria** [comment]
This seems to be a bug in percent encoding the new line char. Will look into it

**Comment by pmaria** [comment]
@tobiasschweizer there was indeed an issue with the percent encoding. Encoding of code points leading to a single hex digit were leading to single digit percent encodings instead of the required 2 digits. This has been fixed with `0` padding. 
So the IRI generated will now be  `https://data.connectome.ch/author/Aad%20van%20der%0A%20%20%20%20%20%20%20%20%20%20%20%20Lugt` in this case.

**Comment by tobiasschweizer** [comment]
That's great! Thanks for the explanation and the quick fix!

I was wondering if the RML specs actually define how an IRI/URI encoding looks like given some string. 

For example, "A Bergström" gives <https://data.connectome.ch/author/A%20Bergström> (space is URL encoded) with CARML and <https://data.connectome.ch/author/A%20Bergstr%C3%B6m>  (space and "ö" are URL encoded) with RML Mapper.

**Comment by pmaria** [comment]
It is specified in the R2RML spec: https://www.w3.org/TR/r2rml/#dfn-iri-safe. However, I must admit I haven't ever looked at the implementation in detail. And, I'm now not sure `ö` shouldn't be encoded. Looking at the IRI-safe part, I believe it actually should be encoded. I'll take a deeper look and get back to you.

**Comment by tobiasschweizer** [comment]
> It is specified in the R2RML spec: https://www.w3.org/TR/r2rml/#dfn-iri-safe. However, I must admit I haven't ever looked at the implementation in detail. And, I'm now not sure `ö` shouldn't be encoded. Looking at the IRI-safe part, I believe it actually should be encoded. I'll take a deeper look and get back to you.

Let me know if I can help investigating that. Specs can be quite tricky sometimes (at least for me) ...

**Comment by pmaria** [comment]
Yes please. Any help is appreciated :)

**Comment by pmaria** [comment]
Looking specifically at `ö` the transformation seems correct, since it falls within `%xA0-D7FF` of `ucschar`. See https://qaz.wtf/u/show.cgi?show=+%25xA0-D7FF&type=hex.

**Comment by tobiasschweizer** [comment]
Looking at the definition of an IRI (as opposed to a URI):

> IRIs extend URIs by using the [Universal Character Set](https://en.wikipedia.org/wiki/Universal_Character_Set), where URIs were limited to [ASCII](https://en.wikipedia.org/wiki/ASCII), with far fewer characters.

(https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier#Syntax)

I think https://data.connectome.ch/author/A%20Bergstr%C3%B6m is a correct IRI. Looking at https://data.connectome.ch/author/A%20Bergstr%C3%B6m I guess this is rather a URI than an IRI. Maybe we could open a topic on https://github.com/kg-construct/rml-questions/discussions/ to discuss the question whether an RML engines should produce an IRI or a URI or if this could be made configurable in some way.

**Comment by pmaria** [comment]
Yes, IRI's have a much larger range of unescaped characters for internationalization purposes. And all W3C specs now use the IRI spec. Still it might be useful to be able to force URI generation from the mapping. This makes implementing linked data dereferencing a lot easier for example, since HTTP does not support IRIs.

**Comment by pmaria** [comment]
Would be good to discuss indeed

**Comment by tobiasschweizer** [comment]
Yes, because the URI and IRI versions are not considered equal, at least not by the [tool](https://rdflib.readthedocs.io/en/stable/_modules/rdflib/compare.html) I am using to check for differences between the output of different RML engines given the same data and mapping. Would you like to open a topic on https://github.com/kg-construct/rml-questions/discussions/ or should I do it?

**Comment by pmaria** [comment]
If you could, that would be great :)

**Comment by tobiasschweizer** [comment]
ok, will do :-)

**Comment by tobiasschweizer** [comment]
And here we go: https://github.com/kg-construct/rml-questions/discussions/28

Please feel free to add any missing details etc.
