### ISSUE TITLE
XPaths and namespaces

### ISSUE THREAD

**Issue by syats** [carml/carml#28]
Hi again,

I will start by saying I know how contentious the issue of namespaces in XPaths is!
Having said that, I find no workaround to be able to map XML files that use namespaces, except using the name() construct all over the XPath.

Here is a sample file: 
https://pycsw.eodc.eu/?service=CSW&version=3.0.0&elementsetname=full&request=GetRecordById&outputSchema=http://www.isotc211.org/2005/gmd&id=S2A_MSIL1C_20170802T020451_N0205_R017_T51MYM_20170802T020833

If I want to get the node gmd:MD_Metadata/gmd:fileIdentifier/gco:CharacterString  all I've been able to do is construct an mapping like this:

`    rr:subjectMap [        
	rr:termType rr:IRI;
        rr:template "http://dma.at/data_assets/{./*[name()='gmd:fileIdentifier']/*[name()='gco:CharacterString']}";
        rr:class ex:DataAsset;
    ];  `

It is not a very elegant solution.

Taking a quick look at the angry responses of the developer of Saxon, I see that there is some way to pass the namespaces to the XPathCompiler. https://social.msdn.microsoft.com/Forums/sqlserver/en-US/0111dde0-67c8-4b0a-9348-d735428c071a/xpath-and-namespace-issue?forum=xmlandnetfx  

Do you think it makes sense to pass all the namespaces in the mapping file into the compiler? Or at least give an option to do this?
I know that including it by default might cause great confusion if people name two different namespaces the same in the mapping and in the input file, that's why maybe making it optional might be a good idea.

Any thoughts on this? 
Do you think it is preferable to stick with the horrible name() idiom?

Thanks in advance!

**Comment by pmaria** [comment]
Hi @syats,

I agree. I actually ran into the same issue.
I see several options on how to approach this, which I am now contemplating. But I think we can add support for this in the next release.

**Comment by pmaria** [comment]
@syats, will be part of next release
