### ISSUE TITLE
multiReference with "multilanguage"

### ISSUE THREAD

**Issue by mdavino** [carml/carml#39]
is it possibile carml:multiReference with "multilanguage"?

{
     "id": "112",
     "name": 
     [
        {
              value: 'Giuseppe',
              language: 'it'
       } ,
         {
              value: 'Joseph',
              language: 'en'
       } ,
     ] 
}

for get:

ex:id112 a exPerson ;
     ex:name 'Giuseppe'@it ;
     ex:name 'Joseph'@en .

Thanks.

**Comment by pmaria** [comment]
Hi @mdavino,

No, there is no support for matching languages with multiReference.

To solve your example you can filter values with specific languages using json path:

```
<#Person> 
  rml:logicalSource <#LS> ;
  rr:subjectMap [
    rr:template "http://example.com/id{id}";
    rr:class ex:Person ;
  ] ;
  rr:predicateObjectMap 
    [
      rr:predicate ex:name ;
        rr:objectMap [
          rml:reference "name[?(@.language == 'it')].value" ;
          rr:language "it" ;
        ] ;
    ] ,
    [
      rr:predicate ex:name ;
        rr:objectMap [
          rml:reference "name[?(@.language == 'en')].value" ;
          rr:language "en" ;
        ] ;
    ]
.
```

**Comment by VladimirAlexiev** [comment]
R2rml and rml also don't support getting the language tag from a source field. So search for `rrx:languageColumn`

**Comment by pmaria** [comment]
Hi @VladimirAlexiev ,
Thanks for pointing this extension out. Are there any other extensions defined under this namespace? At least this one would indeed be interesting to add to RML.

**Comment by VladimirAlexiev** [comment]
That's the only one. It's implemented in db2triples (https://github.com/antidot/db2triples/issues/13) and perl (http://search.cpan.org/~tobyink/RDF-RDB2RDF-0.008/lib/RDF/RDB2RDF/R2RML.pm)

**Comment by pmaria** [comment]
Language map is now available
