### ISSUE TITLE
LogicalSource inside functionValue ignored

### ISSUE THREAD

**Issue by fbuciuni90** [carml/carml#56]
Does functionValue use the rml:logicalSource specified inside it?
In particular I need to use multiple logicalSource, one for a functionValue in subjectMap 
and another for a functionValue in predicateObjectMap, however it looks like the logicalSource given
inside the functionValue is ignored so I don't get the (correct) predicateObjectMap.
I attach a piece of code to clarify what I'm trying to do.
[issue.rml.zip](https://github.com/carml/carml/files/2227535/issue.rml.zip)
Thanks.

**Comment by pmaria** [comment]
Hi @fbuciuni90 ,

No the logical source inside the functional term map is ignored. The logical source of the triples map which references the functional term map is used for it's execution. 

What you want to achieve doesn't seem to be supported at the moment. There would have to be a way to join a functional term map's iteration with the triples map's iteration.

What you can do in your case is use a referencing object map from <#MappingSchedaOA> to join to the subject generated by  <#MappingSchedaOA_Time>.

Something like:
```
<#MappingSchedaOA>
	rr:predicateObjectMap [
		rr:predicate cbcv_prop:notizieCronologicheRelative;
		rr:objectMap [
			rr:parentTriplesMap <#MappingSchedaOA_Time> ;
			# joinCondition to join the two iterations
			rr:joinCondition [
				rr:child "some value from <#json_schedaOA>" ;
				rr:parent "some value from <#json_schedaOAtime>" ;
			] ;
	] ;
.
```

**Comment by fbuciuni90** [comment]
Ok, I see how the logical source is used.

I've already tried to use the joinCondition but it doesn't return the correct result in my case.
In particular, since in <#MappingSchedaOA_Time> I have two properties, I need to use two multiJoinConditions. The problem arises because, in the json source I'm using, some instances have one property missing and so rr:child has a jsonpath 
(something like ['DT'][*].['DTZ.DTZG'] following the example attached before) which iterates over missing paths returning an error.

**Comment by pmaria** [comment]
It's hard to see what the problem is without the input json file.

>'ve already tried to use the joinCondition but it doesn't return the correct result in my case.
In particular, since in <#MappingSchedaOA_Time> I have two properties, I need to use two multiJoinConditions.

Note that you can add multiple rr:joinCondition nodes to a referencing object map.

> The problem arises because, in the json source I'm using, some instances have one property missing and so rr:child has a jsonpath
(something like ['DT'][*].['DTZ.DTZG'] following the example attached before) which iterates over missing paths returning an error.

Is this perhaps the same error as was reported in issue #55 ?

**Comment by fbuciuni90** [comment]
The error displayed is different than the one reported in issue #55 (but may be related). 
I get this error 
```shell
Caused by: java.lang.NullPointerException: null 
```
I attach a standalone example to show why the join doesn't actually work in my case.

https://drive.google.com/file/d/1McmPIONHUCE6KLDSam1M4iCq1hIA_bfb/view?usp=sharing

Thanks.

**Comment by fbuciuni90** [comment]
I'd like to report that I found a solution to the problem using multiTemplate into the functions and some filters to solve the jsonpath issue.
If you are interested in, I uploaded the example attached before, where the new mapping has name "mapping3.rml.ttl".
https://drive.google.com/file/d/1McmPIONHUCE6KLDSam1M4iCq1hIA_bfb/view?usp=sharing
The side issue of this approach is that it may turns out to be very long to set up, because in general the number of object property declarations grows up with the number of properties. 
Thanks.

**Comment by pmaria** [comment]
@fbuciuni90 that's great! Thanks for letting us know.

I was just looking into the issue. It seems that joins with filter expressions that return a collection with a null value aren't handled properly. I'll fix this and hopefully release it soon.
