### ISSUE TITLE
Rename *impl classes

### ISSUE THREAD

**Issue by pmaria** [carml/carml#6]

**Comment by ZacharyWhitley** [comment]
What would you like them renamed to?

**Comment by pmaria** [comment]
@ZacharyWhitley would like to rename them to Carml*. So for example SubjectMapImpl becomes CarmlSubjectMap.

**Comment by ZacharyWhitley** [comment]
Submitted PR

**Comment by pmaria** [comment]
Thanks @ZacharyWhitley !! Looks good to me. Really cool that you picked this up.

**Comment by ZacharyWhitley** [comment]
My pleasure. Really cool of you to write carml! :)
