### ISSUE TITLE
Store result in triple store database

### ISSUE THREAD

**Issue by SebeiHiba** [carml/carml#64]
Hi, 
How can I store the org.eclipse.rdf4j.model.Model in an RDF Triple Store?

**Comment by pmaria** [comment]
Hi @SebeiHiba,

That depends on which triple store you're using.
The easiest is if your triple store has an RDF4J binding. Then you can directly add your org.eclipse.rdf4j.model.Model to your store.

See http://docs.rdf4j.org/programming/#_the_repository_api and http://docs.rdf4j.org/programming/#_rdf_collections_and_repositoryconnections

If not, you will have to translate the org.eclipse.rdf4j.model.Model to something your triple store API supports.

**Comment by SebeiHiba** [comment]
Hi !!! first Thank you for your response. 
I tried to store as this
RDF4JStore rmlStore = new RDF4JStore(model);
Executor executor = new Executor(rmlStore, new RecordsFactory(new DataFetcher(cwd, rmlStore)));

But the RDF4JStore is not defined. (The package be.ugent.rml.store is not available) so now I want to store it with OpenLink Virtuoso.

**Comment by pmaria** [comment]
There is a RDF4J connector for Virtuoso. See http://vos.openlinksw.com/owiki/wiki/VOS/VirtSesame2Provider. I have no experience with Virtuoso, but It seems pretty straight forward to use.

The be.ugent.rml.store.RDF4JStore is not part of CARML but of RMLio's rml-mapper, so I don't know what that does.

**Comment by pmaria** [comment]
Closing as not related to CARML functionality
