### ISSUE TITLE
UTF-8 encoding on labels

### ISSUE THREAD

**Issue by nicky508** [carml/carml#66]
Best,

At the moment I have a dataset with lots of terms words with special characters like ä ö etc. But it seems the characters are not encoded and therefore, I got ?? signs in SPARQL results instead of the proper character for example.

**Comment by ktk** [comment]
I've had this with multiple input files, XML input is encoded in UTF-8, output strings get encoded to something that is definitely not UTF-8 anymore. German umlauts is an easy testcase.

**Comment by pmaria** [comment]
Interesting. Is it possible to provide a test case?

**Comment by ktk** [comment]
I can cook something up. I use it via https://github.com/netage/carml-cli by @nicky508. Not sure on what side the UTF gets lost.

Will update here

**Comment by pmaria** [comment]
Cool thanks!

**Comment by ktk** [comment]
OK this is weird, I created the following input XML file and carml-config: https://gist.github.com/ktk/2a5e81ca079c74612b9b096e7720f51b

I use [carml-cli](https://github.com/netage/carml-cli) from @nicky508 to convert it:

   java -jar cli-0.0.6-SNAPSHOT-jar-with-dependencies.jar -i utf-test.xml -m utf-test.ttl -of ttl -o utf-out.ttl

or 

    java -jar cli-0.0.6-SNAPSHOT-jar-with-dependencies.jar -i utf-test.xml -m utf-test.ttl -of nt -o utf-out.nt

Result on my mac (BSD subsystem):

```turtle
<http://example.org/1> a <http://example.org/UTF>;
  <http://example.org/english> "This is english text";
  <http://example.org/french> "Un texte en français";
  <http://example.org/german> "Das wäre ein Text in Deutsch";
  <http://example.org/japanese> "スプーンはありません" .
```

-> looks perfectly fine.

if I do that on Linux I get:

```turtle 
<http://example.org/1> a <http://example.org/UTF>;
  <http://example.org/english> "This is english text";
  <http://example.org/french> "Un texte en fran��ais";
  <http://example.org/german> "Das w��re ein Text in Deutsch";
  <http://example.org/japanese> "������������������������������" .
```
Which looks like double-encoding to me.

I used one of our docker-containers for the linux-environment: https://hub.docker.com/r/zazukoians/node-java-jena/, Java 8 based, same version I have on my mac.

Any ideas how this is possible?

**Comment by pmaria** [comment]
Might be a problem with reading the input file. If carml-cli doesn't specify the input encoding, then it is probably defaulting to standard encoding of the OS, which is usually a bad idea.
I could check this later, when I'm behind a pc.

**Comment by nicky508** [comment]
On my windows pc it looks fine as well. That is probably the issue. Take a look at it tommorow

**Comment by pmaria** [comment]
I checked the standard encoding in a docker container from the `zazukoians/node-java` image. This is `ANSI_X3.4-1968` aka US-ASCII. So I believe carml-cli is reading the input file as ASCII. That would indeed explain it.

**Comment by ktk** [comment]
Tnx @pmaria. What would be the proper way to handle that, take it as utf-8 by default or read out the encoding in the xml itself

**Comment by pmaria** [comment]
If you know your input files encoding upfront, you can either default to an encoding when creating the inputstream, or make it parameterizable via de CLI.
If you don't know the encoding upfront it is more complicated. There is no exact way of determining the encoding of a file. There are utils like [Apache Tika's CharsetDetector](https://tika.apache.org/1.19/api/org/apache/tika/parser/txt/CharsetDetector.html) which you could use. But it is advisable, if feasible, to check the resulting data for Unicode replacement characters, if by chance a wrong encoding was determined.

**Comment by ktk** [comment]
Thanks @pmaria, I've set my docker image to UTF now with [this commit](https://github.com/zazukoians/docker-node-java/commit/4f00a8e8986b07bc20fe86aff68db0b18d629f92). That fixed it!

We can close this issue. BTW are you interested in shipping @nicky508 CLI interface with carml or should we keep that separately?

**Comment by pmaria** [comment]
Great!

> We can close this issue. BTW are you interested in shipping @nicky508 CLI interface with carml or should we keep that separately?

We could look and see if we can combine it with https://github.com/pmaria/carml-jar. Most notably the FnO function loading. However, that project wat thrown together pretty quickly and also needs some work. I'll chat with @nicky508 to see what we can do.

Closing this issue.
