### ISSUE TITLE
Blank nodes in XML structures

### ISSUE THREAD

**Issue by ktk** [carml/carml#67]
I have a bit a hard time understanding how I would create blank nodes for xml elements that are nested. Currently I have a structure like this (simplifyed):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
	<services>
		<service>
			<url_identifier>
				geo-ubs-bancomat-46c1
			</url_identifier>
			<geo itemprop="geo" itemtype="http://schema.org/GeoCoordinates">
				<meta content="47.54642649358809" itemprop="latitude"/>
				<meta content="7.588017409361333" itemprop="longitude"/>
			</geo>
		</service>
	</services>
</root>
```

I map the main element like this:

```turtle
<#Place> a rr:TriplesMap ;
  rml:logicalSource [
    rml:source [
      a carml:Stream ;
    ] ;
    rml:referenceFormulation ql:XPath ;
    rml:iterator "/root/services/service" 
  ] ;

  rr:subjectMap [
    rr:template "http://lod.opentransportdata.swiss/place/{url_identifier}" ;
    rr:class schema:Place ;
    rr:termType rr:IRI 
  ] ;

  rr:predicateObjectMap [
		rr:predicate schema:geo;
		rr:objectMap [
			rr:template "http://lod.opentransportdata.swiss/place/{url_identifier}#geo" ;
      rr:termType rr:IRI 
		];
  ] ;
.
```
and the geo part like this:

```turtle
<#GeoCoordinates> a rr:TriplesMap ;
  rml:logicalSource [
    rml:source [
      a carml:Stream ;
    ] ;
    rml:referenceFormulation ql:XPath ;
    rml:iterator "/root/services/service" 
  ] ;

  rr:subjectMap [
    rr:template "http://lod.opentransportdata.swiss/place/{url_identifier}#geo" ;
    rr:class schema:GeoCoordinates ;
    rr:termType rr:IRI 
  ] ;


 rr:predicateObjectMap [
		rr:predicate schema:latitude;
		rr:objectMap [
			rml:reference  './geo/meta[@itemprop="latitude"]/@content';	
		];
 ];

 rr:predicateObjectMap [
		rr:predicate schema:longitude;
		rr:objectMap [
			rml:reference  './geo/meta[@itemprop="longitude"]/@content';	
		];
 ];
.
```
Unfortunately hash-URIs are not well handled in triplestores so dereferencing gets hard that way.

So I would like to switch that to blank nodes but I fail to see how the construct would look like, I suppose I need some form of join to get blank nodes working properly in this structure? I could not find an example like this in the RML spec.

Any hints are much appreciated :)

**Comment by pmaria** [comment]
@ktk in CARML we follow the R2RML spec in this case. You can create a blanknode with a specific template.  So basically you create a termMap with an `rr:template` and `rr:termType rr:BlankNode`. This will allow you to achieve "joined" blanknodes on template in the resulting data.  See also https://www.w3.org/TR/r2rml/#generated-rdf-term

**Comment by ktk** [comment]
@pmaria tnx will check it out tomorrow. If I get it to work I will add a sample in the readme if this is ok for you.

**Comment by pmaria** [comment]
Closing this as considered not an issue.
