### ISSUE TITLE
Carml and Big data ingestion Tools

### ISSUE THREAD

**Issue by DevAnonymous-dev** [carml/carml#75]
Hi! 

Can I ingest batch social networks data such as tweets into CARML using one of the big data ingestion tools such as NIFI , Flume or Kafka?

Regards,
Hiba

**Comment by pmaria** [comment]
Hi @SebeiHiba ,

I wouldn't recommend trying to load large data sources into CARML. CARML in it's current state works best for relatively small sources. Support for larger sources is on the top of our roadmap.

So, you could use CARML for large sources as long as you have a process that chunks the source in some way and maps those chunks using CARML.

**Comment by SebeiHiba** [comment]
Hi!
 thank you for your response. Actually I was talk about the ability to connect 
 CARML and Apache Kafka as in showing in this **presentation slide 38** [https://fr.slideshare.net/gschmutz/ingesting-streaming-data-into-graph-database](url). The tweet will not be large but I will have a big number of tweets (millions of tweets) that will be mapped one by one into RDF through CARML.
Best Regards,


1

**Comment by pmaria** [comment]
Ah yes! Thanks for pointing out this presentation. That's very cool.
So yes, streaming it in that way should definitely be possible.

**Comment by SebeiHiba** [comment]
But actually no java example is provided that can explain the connection between Kafka and CARML

**Comment by pmaria** [comment]
That's true. CARML is independent of these data pipelining frameworks. 
But this part of the documentation is relevant here: https://github.com/carml/carml#input-stream-extension.

So, if you can create an inputstream from a chunk during your processing with Kafka, you can bind it to a CARML `RmlMapper` instance.
