### ISSUE TITLE
Declare multiple namespaces

### ISSUE THREAD

**Issue by nicky508** [carml/carml#77]
Is it possible to declare multiple namespaces. Right now I have a xml file with nested namespaces:

```
<?xml version="1.0" encoding="UTF-8"?>
<nena-ne:NotifyBodies xmlns="urn:oasis:names:tc:emergency:cap:1.1" xmlns:nena-ne="urn:nena:xml:ns:NotifyEventExchange:2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edxl-cap="http://release.niem.gov/niem/adapters/edxl-cap/3.0/" xsi:schemaLocation="urn:nena:xml:ns:NotifyEventExchange:2.0 ../exchange/2.0/NotifyEventPackageExchange.xsd">
	<edxl-cap:AlertAdapter>
		<alert>
			Content
		</alert>
		<alert>
			Content
		</alert>
	</edxl-cap:AlertAdapter>
</nena-ne:NotifyBodies>
```

With the following mapping I get nothing back:

```
<#SubjectMapping> a rr:TriplesMap ;
  rml:logicalSource [
    rml:source [
      a carml:Stream ;
	  carml:declaresNamespace [
	           carml:namespacePrefix "nena-ne" ;
                   carml:namespaceName "urn:nena:xml:ns:NotifyEventExchange:2.0/" ;
      ] ;
    ] ;
    rml:referenceFormulation ql:XPath ;
    rml:iterator "/nena-ne:NotifyBodies/AlertAdapter/alert" ;
  ] ;

  rr:subjectMap [
    rr:template "http://data.nena.org/alert/{./identifier}" ;
    rr:class nena:Alert ;
    rr:termType rr:IRI ;
  ] ;
  
  rr:predicateObjectMap [
		rr:predicate dcterms:identifier;
		rr:objectMap [
			rml:reference "identifier"
			rr:datatype xsd:String;
		];
  ] .
  
```

Probably because I am missing the namespace for "AlertAdapter", is there a way to specify this nested namespace as well?

**Comment by nicky508** [comment]
Is this the right way:

`<#SubjectMapping> a rr:TriplesMap ;
  rml:logicalSource [
    rml:source [
      a carml:Stream ;
	  carml:declaresNamespace [
        carml:namespacePrefix "edxl-cap" ;
        carml:namespaceName "http://release.niem.gov/niem/adapters/edxl-cap/3.0/" ;
      ] ;
	  carml:declaresNamespace [
		carml:namespacePrefix "nena-ne" ;
        carml:namespaceName "urn:nena:xml:ns:NotifyEventExchange:2.0/" ;
      ] ;
    ] ;
    rml:referenceFormulation ql:XPath ;
    rml:iterator "/nena-ne:NotifyBodies/edxl-cap:AlertAdapter/alert" ;
  ] ;`

**Comment by pmaria** [comment]
Yes, that should work.

**Comment by nicky508** [comment]
Found the issue why it did not work. there is a default mapping as well. I declare the default namespace with a self-chosen prefix and added this prefix to the elements. Now it works!
