### ISSUE TITLE
Support for 1-N, N-M join conditions

### ISSUE THREAD

**Issue by dachafra** [carml/carml#78]
At the moment my original data contains joins of the type 1-N, N-1, N-M CARML isn't able to generate the corresponding RDF. The output message is:

"Expecting single value for referencing object map on subject [SUBJECT], and predicate [PREDICATE]. Multiple values found."

**Comment by pmaria** [comment]
Hi @dachafra,

CARML handles these cases with this extension: https://github.com/carml/carml#multitermmap-extension 

The reason for this is the fact that this behavior is not defined by RML. This is also discussed in #52 .

**Comment by dachafra** [comment]
Thanks @pmaria, I would recommend you to add this info in the error message, it would very useful. 

I also see that you mention that this behaviour is not defined by RML, but as RML is an extension of R2RML, anything that isn't defined in RML should follow R2RML. I could agree about the carml:multiReference and carml:multiTemplate as they are cases that I think they don't happen in RDB, but in the case of the joinCondition, R2RML sais (https://www.w3.org/TR/r2rml/#foreign-key): 

"A referencing object map allows using the subjects of another triples map as the objects generated by a predicate-object map. Since both triples maps may be based on different logical tables, this may require a join between the logical tables. **This is not restricted to 1:1 joins.**"

Maybe I misunderstand the spec but I don't see on the necessity of having another property for joins.

**Comment by pmaria** [comment]
> Thanks @pmaria, I would recommend you to add this info in the error message, it would very useful.
Yes, good idea.

> "A referencing object map allows using the subjects of another triples map as the objects generated by a predicate-object map. Since both triples maps may be based on different logical tables, this may require a join between the logical tables. **This is not restricted to 1:1 joins.**"
>
>Maybe I misunderstand the spec but I don't see the necessity of having another property for joins.

You might be correct there. Though I can't seem to find a test case that corroborates this in https://www.w3.org/2001/sw/rdb2rdf/test-cases/. I'll look into this some more.
