### ISSUE TITLE
Two logical sources for one RML mapping file

### ISSUE THREAD

**Issue by DevAnonymous-dev** [carml/carml#79]

**Comment by DevAnonymous-dev** [comment]
can we use two different logical sources (e.g. two different JSON files) in one RML mapping file

**Comment by pmaria** [comment]
Yes, that's possible. Just specify the source in the appropriate logical source.

**Comment by DevAnonymous-dev** [comment]
I tried this example with the two logical sources: "/home/use/eclipse_projects/Application/src/main/resources/data/tweet.json" and  "/home/user/eclipse_projects/Application/src/main/resources/data/media.json" but I get the error Logical sources are not equalParent.

@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .
@prefix carml: <http://carml.taxonic.com/carml/> .
@prefix model: <http://localhost/model#>. 
@prefix dc: <http://purl.org/dc/elements/1.1/>.  
@prefix ns: <http://www.w3.org/2003/06/sw-vocab-status/ns#>. 
@prefix owl: <http://www.w3.org/2002/07/owl#>.  
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.    
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.  
@prefix fno: <http://semweb.datasciencelab.be/ns/function#> .



    <#TextFeaturesMapping> a rr:TriplesMap ;
  rml:logicalSource [
	rml:source "/home/use/eclipse_projects/Application/src/main/resources/data/tweet.json";
    rml:referenceFormulation ql:JSONPath;
      rml:iterator "$"
    ];

 rr:subjectMap [
    rr:template "http://localhost/socialNetwork/model/{id}/TextFeatures" ;
  rr:class  model:TextFeatures;
  ] ;
    rr:predicateObjectMap [
    rr:predicate model:hasTopic ;
    rr:objectMap [
      rml:reference "$.text";
    ]] ;
    
    rr:predicateObjectMap [
    rr:predicate model:hasEmbededMedia ;
    rr:objectMap [
      rr:parentTriplesMap <#EmbeededMediaMapping>;
    ]] .

 <#EmbeededMediaMapping> a rr:TriplesMap ;
  rml:logicalSource [
	rml:source "/home/user/eclipse_projects/Application/src/main/resources/data/media.json";
    rml:referenceFormulation ql:JSONPath;
      rml:iterator "$"
    ];

 rr:subjectMap [
    rr:template "http://localhost/socialNetwork/model/EmbeededVideo/{id}" ;
rr:class model:EmbeededVideo;
  ] ;

 rr:predicateObjectMap [
    rr:predicate model:hasURL;
    rr:objectMap [
      
      rml:reference "$.URL";
    ]] .

**Comment by pmaria** [comment]
Yes, you are trying to join iterations on different sources, but since the data in these iterations is not the same you must specify a join condition. See http://rml.io/spec.html#relationships-among-logical-sources-rr-parenttriplesmap-rr-joincondition-rr-child-and-rr-parent

**Comment by DevAnonymous-dev** [comment]
thank you for your response the use of join condition resolve the issue of the logical sources but the link between the first subject belongs to the first logical source and the object belongs to the second logical source is not established.
    
    <#TextFeaturesMapping> a rr:TriplesMap ;
  rml:logicalSource [
	rml:source "/home/user/eclipse_projects/app/src/main/resources/data/tweet.json";
    rml:referenceFormulation ql:JSONPath;
      rml:iterator "$"
    ];

 rr:subjectMap [
    rr:template "http://localhost/socialNetwork/model/{id}/TextFeatures" ;
  rr:class  model:TextFeatures;
  ] ;

 rr:predicateObjectMap [
    rr:predicate model:hasEmbeededVideo ;
   rr:objectMap [
      rr:parentTriplesMap <#EmbeededMediaMapping>;
      rr:joinCondition [
        rr:child "videoid";
        rr:parent "$.id";
      ]
    ]] .
    
  <#EmbeededMediaMapping> 
  rml:logicalSource [
    rml:source "/home/user/eclipse_projects/app/src/main/resources/data/media.json" ;
    rml:referenceFormulation ql:JSONPath;
      rml:iterator "$"
  ];
  rr:subjectMap [
  rr:template "http://model/EmbeededVideo/{id}" ;
rr:class model:EmbeededVideo;
  ].

**Comment by pmaria** [comment]
looking at your mapping your probably mixing up child and parent conditions. The child expression is evaluated on the current source, and the parent expression is evaluated on the source to be joined. Also I dont think the `$.` part is necessary in your expression. Make sure the expressions evaluate on the respective sources.
