### ISSUE TITLE
Failing tests when building on Windows

### ISSUE THREAD

**Issue by victorlouw** [carml/carml#99]
These tests fail when building on Windows (tried cmd.exe and Git Bash):
- `com.taxonic.carml.engine.iotests.RmlMapperTest.testIriFunctionMapping`
- `com.taxonic.carml.engine.iotests.PredObjectMapsTest.testPredObjectMappingGOnePredwithJoinCondition`

Everything builds fine on Linux / WSL.

Seems to be an encoding issue (`葉篤正` and `ë` are involved).
I tried specifying `UTF_8` encoding in several places, but to no avail.

**Comment by pmaria** [comment]
This problem seems to have been resolved
